version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents overwriting node_modules
    user: "node"  # Run as the non-root 'node' user

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "15000:5000"
      - "5005:5005"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development