services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app
      - /app/node_modules


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "15000:5000"
      - "5005:5005"
    volumes:
      - ./backend:/app


networks:
  default:
    driver: bridge